### ISSUE TITLE
Problem to switch networks (WalletConnect and OpenSea)

### ISSUE THREAD

**Issue by captainmarshin** [tangem/tangem-sdk-ios#244]
I tried to storing NFTs in Tangem wallet and NFT stuck in wallet.

I was created new OpenSea account via WalletConnect with Tangem Wallet.
Account in Ethereum network.

Wallet: 0x010e96B69615e47112b786A1085E5039796C0a73

After that I transferred NFT from Polygon network to this account.
NFT: https://opensea.io/assets/matic/0x6acb8fb82880d39c2b8446f8778a14d34ee6cfb7/703393
OpenSea supports different networks.

Few time later I tried to transfer this NFT to my another wallet and get this error:
<img width="1273" alt="Screenshot 2022-12-31 at 3 29 39 PM" src="https://user-images.githubusercontent.com/67394582/210130861-a1290157-8947-477e-a595-99b2f6757bea.png">

I tried to manually switch network in Tangem wallet from Ethereum to Polygon.
After that I got new account on OpenSea.
Wallet: 0x630e1380D70dce385bd23908E2933b7F9398A37B

So, for now I have 2 accounts on OpenSea in 2 networks: Ethereum and Polygon.

I tried to Hide Polygon network, login back to my Ethereum account and tried to transfer NFT. After that, I got error message in Tangem App:
<img width="500" src="https://user-images.githubusercontent.com/67394582/210130927-47f6a932-a0f9-4d24-b796-e41e17fc7a1f.png">

I tried to Hide Polygon network, but show Polygon in Ethereum Network. And after that tried to transfer NFT and got this error message again.
<img width="500" src="https://user-images.githubusercontent.com/67394582/210130956-6aa085e2-0526-49ed-ac2b-2c71a2c77b7b.png">

If I choose all available Polygon networks in Tangem and try to transfer NFT - Tangem nothing showing, but error occurred on OpenSea:
<img width="1273" alt="Screenshot 2022-12-31 at 3 29 39 PM" src="https://user-images.githubusercontent.com/67394582/210130861-a1290157-8947-477e-a595-99b2f6757bea.png">

Every action, that requires sign message (Transfer, Sell and etc.) get this error message. So I think, that Tangem App doesn't understand how to switch networks.

After all, NFT stuck on this account and nothing I can do.

Another wallets works fine, no problems to transfer NFTs at all.

**Comment by tureck1y** [comment]
This issue was resolved in the Tangem app repo.

**Comment by captainmarshin** [comment]
In 4.0.1 (latest iOS version) problem is still not fixed. Waiting for next release?

**Comment by tureck1y** [comment]
Please, add a custom Polygon token with the Ethereum derivation and then try to connect to it.

**Comment by captainmarshin** [comment]
Added. Same error...

**Comment by tureck1y** [comment]
Unfortunately, WalletConnect doesn't support switching between chains with different addresses.

To workaround this limitation you should:
- Disconnect from OpenSea
- Add the new Polygon token via the "Add custom token" screen. Select "Ethereum" as the BIP44 coin type. After this, the new Polygon token will appear on the main screen with the same address as Ethereum.
- Then, connect to OpenSea, press "Select Network" and choose the appropriate Polygon network with the correct address.

If this issue still persists, please contact our support via chat or "Send Feedback" and they will do their best to help you.
